sudo: false
language: ruby
cache:
  bundler: true
rvm:
- 2.4.0
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
  - bundle install
script:
- "./image-optimisation.sh"
after_success:
- "./deploy.sh"
branches:
  only:
  - master
notifications:
  email: false
env:
  global:
    secure: "ULNC4gn4eesaJ1qfb/ulVU8kV8nubFg56+A+oviaT4fA1zLuv2AKj1WJGvZ9eea5lieoJhCQ1CkrHy2fa0WlUcU/OCWjGc/dFmc6pm/xEFJB+NI+4jzP0T7Wwf0VER4eIGYkSHZCBhtkDiO5dKdUBQ/DXxSuEDcWjMUjeqjRdwkCoITL99msVADoVReO8e4coBZpkXSaWyzuqAAZ8lg4b6w/HLq2XeHkfE4YGvY+tJMi7Pi2mLF5IblPU9slkfkm1jEVjhQwi3zR0IQTjyDPyHr/3FYJOKdZbL5nbFImYdRN6lTETtUk2gNmSbKugeZWw+ieQj2uCClXDprqzKH8lt2GvsFsV+/xcLrc1t1xZN6EhQGC+Mc+tNKloQtzJTQ3klTRVJLBeMqQiOnXr8vYLY6y6OW0002GxXcEDzc6elVi/QXsFhX9L8sq4ozW3ySOAHtn2LYCm3C2IRJPktDVDVutIgQWUQEjie6v/VP04Q86LIOPZV5xEh+0Mg9G+m5ilA60QVIfGnotDThroV2JWUhSbQhQMD6AwrlyPhEowdhnjzuRoitUeLt1wcOK/KBTK2Ejod5gIyGrnMRBmJpy3Kzm+PDX5mMqb/1yJommmN9RefC/AtvYknBnemYkEdxHM38Y40NEOn+bnJACwVNPP/YX9C/9phcPklKEfXSqj6E="
