# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
source: .tmp/src
destination: .tmp/dist
title: Sebastien Rousseau
author: Sebastien Rousseau
locale: en
email: hello@sebastienrousseau.co.uk
description: Sebastien Rousseau is the founder and CEO of Reedia Limited - a Blockchain, Banking & Financial Services development consultancy based in London, UK.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sebastienrousseau.co.uk" # the base hostname & protocol for your site
# theme: minima
twitter_username: wwdseb
github_username: sebastienrousseau
facebook_username: wwdseb
facebook_id: 10156052650356913
linkedin_username: sebastienrousseau
google_plus_username: +sebastienrousseau
google_analytics: UA-112050664-1

# Build settings
encoding: utf-8
repository: reedia/sebastienrousseau.co.uk
markdown: kramdown
kramdown:
  toc_levels: 1..3
  input: GFM
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
highlighter: rouge
include:
  - .htaccess
  - _pages
excerpt_separator: <!--more-->
keep_files:
  - .git
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .travis.yml
  - "*.sublime-project"
  - "*.sublime-workspace"
  - Capfile
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - README.md
  - tmp
  - vendor/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - yarn.lock

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-twitter-plugin
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-watch
  - jekyll-assets
  - jekyll-redirect-from
  - jekyll-github-metadata
  - autoprefixer-rails

# Jekyll configuration
# permalink: /:title
paginate: 5
paginate_path: "/page:num/"
permalink: none
timezone:  Europe/London
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

assets:
  plugins:
    img: { optim: {}}
  source_maps: false
  sources:
    - assets/fonts
    - assets/icons
    - assets/images
    - assets/javascripts
    - assets/stylesheets
caching:
  path: ".jekyll-cache/assets"
  type: file # Possible values: memory, file
  enabled: true
compress:
  js: '/assets/js/*.js'
  css: '/assets/styles/*.css'
  img: '/assets/**/*.{jpg,png}'
# --
# baseurl: whether or not to append site.baseurl
# destination: the folder you store them in on the CDN.
# url: the CDN url (fqdn, or w/ identifier).
# --
# cdn:
#   baseurl: false
#   destination: false
#   url: null
# --
# These are all default. No need to add them
#   Only use this if you have more.
# --
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
  # - Gemfile
  # - Gemfile.lock
  # - node_modules
  # - vendor/bundle/
  # - vendor/cache/
  # - vendor/gems/
  # - vendor/ruby/
